"""empty message

Revision ID: ff8a9f1bb029
Revises: 
Create Date: 2024-09-28 22:34:22.054762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8a9f1bb029'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mini_admins',
    sa.Column('Username', sa.String(length=256), nullable=False),
    sa.Column('Password', sa.String(length=162), nullable=False),
    sa.Column('Email', sa.String(length=512), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=14), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=True),
    sa.Column('TryNumber', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('PhoneNumber'),
    sa.UniqueConstraint('PublicKey'),
    sa.UniqueConstraint('Username'),
    mysql_charset='utf8',
    mysql_collate='utf8_persian_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('mini_news_letter',
    sa.Column('Email', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('PublicKey'),
    mysql_charset='utf8',
    mysql_collate='utf8_persian_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('mini_news_letters',
    sa.Column('Email', sa.String(length=1024), nullable=False),
    sa.Column('VerifiedAT', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('PublicKey'),
    mysql_charset='utf8',
    mysql_collate='utf8_persian_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('mini_tags',
    sa.Column('Name', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Name'),
    sa.UniqueConstraint('PublicKey'),
    mysql_charset='utf8',
    mysql_collate='utf8_persian_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('mini_users',
    sa.Column('FirstName', sa.String(length=256), nullable=True),
    sa.Column('LastName', sa.String(length=256), nullable=True),
    sa.Column('Username', sa.String(length=128), nullable=False),
    sa.Column('Password', sa.String(length=162), nullable=False),
    sa.Column('Email', sa.String(length=256), nullable=False),
    sa.Column('Address', sa.String(length=2048), nullable=True),
    sa.Column('PhoneNumber', sa.String(length=14), nullable=True),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Password'),
    sa.UniqueConstraint('PhoneNumber'),
    sa.UniqueConstraint('PublicKey'),
    sa.UniqueConstraint('Username'),
    mysql_charset='utf8',
    mysql_collate='utf8_persian_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('mini_admins_log_table',
    sa.Column('IP', sa.BIGINT(), nullable=False),
    sa.Column('AdminID', sa.Integer(), nullable=True),
    sa.Column('Action', sa.TEXT(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['AdminID'], ['mini_admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('PublicKey'),
    mysql_charset='utf8',
    mysql_collate='utf8_persian_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('mini_contact_us',
    sa.Column('Name', sa.String(length=256), nullable=False),
    sa.Column('Email', sa.String(length=512), nullable=False),
    sa.Column('Title', sa.String(length=256), nullable=False),
    sa.Column('Message', sa.String(length=4096), nullable=False),
    sa.Column('is_answered', sa.Boolean(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['mini_admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Name'),
    sa.UniqueConstraint('PublicKey'),
    sa.UniqueConstraint('Title'),
    mysql_charset='utf8',
    mysql_collate='utf8_persian_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('mini_posts',
    sa.Column('AuthorID', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=512), nullable=False),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('Images', sa.JSON(), nullable=False),
    sa.Column('Slug', sa.String(length=256), nullable=False),
    sa.Column('ShortIntro', sa.Text(), nullable=False),
    sa.Column('ReadingTime', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['AuthorID'], ['mini_admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('PublicKey'),
    mysql_charset='utf8',
    mysql_collate='utf8_persian_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('mini_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mini_posts_Slug'), ['Slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_mini_posts_Title'), ['Title'], unique=True)

    op.create_table('mini_stencil_orders',
    sa.Column('Type', sa.String(length=256), nullable=False),
    sa.Column('Size', sa.String(length=256), nullable=False),
    sa.Column('Side', sa.String(length=256), nullable=False),
    sa.Column('Quantity', sa.Integer(), nullable=False),
    sa.Column('Thickness', sa.String(length=256), nullable=False),
    sa.Column('Fiducials', sa.String(length=256), nullable=False),
    sa.Column('Status', sa.String(length=256), nullable=False),
    sa.Column('OtherRequest', sa.String(length=2048), nullable=True),
    sa.Column('File', sa.JSON(), nullable=True),
    sa.Column('Address', sa.String(length=2048), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['mini_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('PublicKey'),
    mysql_charset='utf8',
    mysql_collate='utf8_persian_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('mini_tickets',
    sa.Column('Title', sa.String(length=64), nullable=False),
    sa.Column('Caption', sa.String(length=512), nullable=False),
    sa.Column('Status', sa.Boolean(), nullable=False),
    sa.Column('File', sa.String(length=1024), nullable=True),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['mini_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('File'),
    sa.UniqueConstraint('PublicKey'),
    mysql_charset='utf8',
    mysql_collate='utf8_persian_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('mini_answer_tickets',
    sa.Column('Message', sa.String(length=512), nullable=False),
    sa.Column('AdminID', sa.Integer(), nullable=False),
    sa.Column('TicketID', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PublicKey', sa.String(length=36), nullable=False),
    sa.Column('CreatedTime', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['AdminID'], ['mini_admins.id'], ),
    sa.ForeignKeyConstraint(['TicketID'], ['mini_tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('PublicKey'),
    mysql_charset='utf8',
    mysql_collate='utf8_persian_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('mini_posts2tags',
    sa.Column('PostID', sa.Integer(), nullable=True),
    sa.Column('TagID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['PostID'], ['mini_posts.id'], ),
    sa.ForeignKeyConstraint(['TagID'], ['mini_tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mini_posts2tags')
    op.drop_table('mini_answer_tickets')
    op.drop_table('mini_tickets')
    op.drop_table('mini_stencil_orders')
    with op.batch_alter_table('mini_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mini_posts_Title'))
        batch_op.drop_index(batch_op.f('ix_mini_posts_Slug'))

    op.drop_table('mini_posts')
    op.drop_table('mini_contact_us')
    op.drop_table('mini_admins_log_table')
    op.drop_table('mini_users')
    op.drop_table('mini_tags')
    op.drop_table('mini_news_letters')
    op.drop_table('mini_news_letter')
    op.drop_table('mini_admins')
    # ### end Alembic commands ###
